import '@/styles/global.css';

import { Noto_Sans_JP as notoSansJp } from 'next/font/google';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

import { cn } from '@/utils';

const inter = notoSansJp({ subsets: ['latin'], variable: '--font-sans' });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

const RootLayout = async ({ children, params }) => {
  const { locale } = params;
  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={cn(
          'min-h-dvh bg-white/30 antialiased flex flex-col items-center',
          inter.variable,
        )}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <main className="relative min-h-dvh w-full max-w-md overflow-hidden border border-gray-50 bg-white-dark">
            {children}
          </main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
